### ISSUE TITLE
Add pnpm package manager support to new ( or preferably existing) docker spfx images.  

### ISSUE THREAD

**Issue by MiSomers** [pnp/docker-spfx#102]
Please add  package manager to the upcoming docker images ( or ideally to all or the more recent previous docker images as well.)

**Comment by waldekmastykarz** [comment]
Great idea! What versions would you be interested in seeing updated?

**Comment by undomil** [comment]
Hi @waldekmastykarz ,
Speaking for myself, I would like to have this included in the 1.17.0 onwards. (so also in the upcoming docker versions)

Thanks in advance and thanks for providing the docker images as they have been of great value the last 6 years!

**Comment by waldekmastykarz** [comment]
My pleasure! Let's start with v1.17 and we can always get back to older versions if need be. I'll keep you updated of the progress.

**Comment by undomil** [comment]
Thanks @waldekmastykarz !

**Comment by waldekmastykarz** [comment]
I published a new image for SPFx v1.20.0 with pnpm. If you could please test it and confirm that this setup works for you, I'll go on an update older images.

**Comment by waldekmastykarz** [comment]
All images starting from v1.17.0 are now updated with pnpm

**Comment by MiSomers** [comment]
@waldekmastykarz  - thank you so much for this!

**Comment by waldekmastykarz** [comment]
My pleasure! Thank you for bringing it up
