### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by garrytrinder** [pnp/docker-spfx#28]
I recently noticed that Docker was using 340% CPU when running the image in a container, this led to machine running hot most of the time. This was using Docker 2.0.0.3 (latest) on MacOS Mojave.

Issue described [here](https://forums.docker.com/t/com-docker-hyperkit-up-cpu-to-340/13057/75) and seems to be pretty common with Docker.

If you are coming across the same issue, a quick fix is to add the `:cached` flag to the volume mount, after doing this my CPU load has dropped massively and I have a much cooler machine.

```
docker run -it --rm --name <name> -v ${PWD}:/usr/app/spfx:cached -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx:1.4.1
```

**Comment by waldekmastykarz** [comment]
Nice suggestion. Thank you!

**Comment by waldekmastykarz** [comment]
Closing as there's nothing for us to change
