### ISSUE TITLE
Access to host files in Linux

### ISSUE THREAD

**Issue by shurick81** [pnp/docker-spfx#37]
When I run this container in Linux, it throws error when trying to write to user hiles on the host, so I cannot also use spfx framework. However the same operation works in node:10.18.1 container:

```
aleks@vm-dev:~/projects/01$ sudo docker run -it --rm --name spfx-helloworld -v $(pwd):/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx /bin/bash -c "mkdir 17"
mkdir: cannot create directory '17': Permission denied
aleks@vm-dev:~/projects/01$ sudo docker run -it --rm --name spfx-helloworld -v $(pwd):/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 node:10.18.1 /bin/bash -c "mkdir /usr/app/spfx/18"
aleks@vm-dev:~/projects/01$ ls
13  15  16  18
```

Might it have something to do with the way we setup permissions in waldekm/spfx?

Linux machine is provisioned in Azure, from this image:

```
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "20.04.202007290"
```

**Comment by waldekmastykarz** [comment]
I see that in the first case you're using just the folder name, whereas in the other case you use the full path. Could it be that you're trying to create the folder in a folder where you don't have the access to?

**Comment by waldekmastykarz** [comment]
When you execute the `ls` commands, what's the working folder? Could it be that the current user doesn't have permissions to access it?

**Comment by mzietlow** [comment]
Not sure if this is related or useful to anyone, but to run under Linux, I had to:
1.) Find the UID of the spfx user (1001 in the following)
2.) Create a folder for the deployment (deployment in the following)
3.) Inside ./deployment create a file (npm-shrinkwrap.json) according to https://stackoverflow.com/a/60921145
4.) run sudu chown -R 1001:1001 ./deployment
5.) cd ./deployment
6.) docker run -it --rm --name ${PWD##*/} -v $PWD:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx
7.) yo @microsoft/sharepoint and follow the setup
8.) Open a new console and run sudo vim ./deployment/config/serve.json
8.1) set the https entry to false
8.2) remove the s from https in the initialPage entry

I was unable to deploy with SSL, but that wasn't a requirement for my small demo anyways

**Comment by shurick81** [comment]
Hi, thanks for your experience @mzietlow! I can share my experience with using WSL2 in Windows. I did not have to create the npm-shrinkwrap.json file. What I had to do is only running this command in the project directory in WSL2 console:

```
sudu chown -R 1001:1001 .
```
