### ISSUE TITLE
spfx:1.4.1 - Sharepoint onprem - Permission Denied

### ISSUE THREAD

**Issue by rezmes** [pnp/docker-spfx#51]
Hi there, I can not understand where is my mistake: 

OS: Windows 10

Docker Desktop v3.5.2 setting > General > Use the WLS 2 based engine is ticked

Using Windows Terminal which has been running as administrator, I ran this command in a Ubuntu terminal:

docker run -it --rm --name ${PWD##*/} -v $PWD:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx:1.4.1

And then after running the container, using this command: npm -g ls -depth=0 checked it, but got this error:

npm ERR! invalid: minizlib@1.0.3 /usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib

![image](https://user-images.githubusercontent.com/19559077/135182889-1f09f172-9bef-4604-ae67-49b29edcd02c.png)

After running gulp serve I got this error:

[10:06:01] Error - 'copy-static-assets' sub task errored after 14 s
EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/ScriptEditorWebPart.manifest.json'
{ Error: EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
errno: -1,
code: 'EPERM',
syscall: 'chmod',
path: '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css' }
[10:06:01] Error - Unknown
EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
{ Error: EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
errno: -1,
code: 'EPERM',
syscall: 'chmod',
path: '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts' }
[10:06:01] Error - Unknown
EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
[10:06:01] ==================[ Finished ]==================
Warning - [spfx-serve] When serving in HTTPS mode, a PFX cert path or a cert path and a key path must be provided, or a dev certificate must be generated and trusted. If a SSL certificate isn't provided, a default, self-signed certificate will be used. Expect browser security warnings.
Error - 'copy-static-assets' sub task errored after 14 s
EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/ScriptEditorWebPart.manifest.json'
Error - Unknown
EPERM: operation not permitted, chmod '/usr/app/spfx/lib/webparts/scriptEditor/components/ScriptEditor.module.css'
Error - Unknown
EPERM: operation not permitted, chmod '/usr/app/spfx/src/webparts/scriptEditor/components/ScriptEditor.module.scss.ts'
[10:06:02] Project pnp-script-editor version: 1.0.0
[10:06:02] Build tools version: 3.2.7
[10:06:02] Node version: v8.9.4
[10:06:02] Total duration: 1.33 min
[10:06:02] Task warnings: 1
[10:06:02] Task errors: 5
[10:06:02] Error - 'undefined' errored after
"orchestration aborted"
[10:06:02] Error - 'undefined' errored after
"orchestration aborted"
![image](https://user-images.githubusercontent.com/19559077/135182933-f6b6968b-1e76-4c0e-8c7b-b87834dc514c.png)

And finaly in browser I get this error:

manifests.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
sp-loader-assembly_en-us.js:16841 Beacon: To disable logging to the console set "window.disableBeaconLogToConsole = true" in the debug window
sp-loader-assembly_en-us.js:20952 Beacon: To disable logging to the console set "window.disableBeaconLogToConsole = true" in the debug window
workbenchInit.js:8 Uncaught TypeError: Cannot read property 'getManifests' of undefined
at workbenchInit.js:8
sp-loader-assembly_en-us.js:5428 Uncaught (in promise) Error: ***Invalid preloaded data.
at sp-loader-assembly_en-us.js:5428
DevTools failed to load source map: Could not load content for https://localhost:4321/node_modules/@microsoft/sp-webpart-workbench/node_modules/@microsoft/sp-loader/dist/sp-core-library_en-us.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
![image](https://user-images.githubusercontent.com/19559077/135183013-e2684119-9313-4f62-9564-dfb97ee9ccc8.png)

**Comment by shurick81** [comment]
@rezmes could you give some more details?

1. Have you enabled Docker to write to the current working directory?
2. Did you create/scaffold this project using this docker? Or was it created somewhere else and then you just attach the existing project directory to the container?
3. Did you install the project dependencies using this docker? I mean where did you run `npm install` for this directory in container or somewhere else?
4. Have you tried scaffolding a new project using this docker and installing the dependencies? That could help localize issues I hope.

**Comment by waldekmastykarz** [comment]
Closing due to lack of response
