### ISSUE TITLE
Question: Should We Update Node Image?

### ISSUE THREAD

**Issue by shurick81** [pnp/docker-spfx#56]
1. Should we always try to inherit from the latest node image when we update the docker-spfx image for other reasons?
2. Should we always update the docker-spfx image when there is a new node image?

**Comment by waldekmastykarz** [comment]
SPFx depends on a specific major version, eg. for v1.13.0 we need Node@14. We could upgrade to the latest Node@14 image but we need to stay on that major version.

**Comment by shurick81** [comment]
So we should not update now to 14.18.3, for example?

**Comment by shurick81** [comment]
If we update, it might affect stability of the current jobs that depend on existing image tags...

**Comment by waldekmastykarz** [comment]
Theoretically, it shouldn't do any harm to update to the latest supported version in the given range. On the other hand, someone would need to test it, and what's really the benefit of doing it?
