### ISSUE TITLE
5432 port exposed

### ISSUE THREAD

**Issue by shurick81** [pnp/docker-spfx#68]
We did not quite finished with removing port 5432 from the latest SPFx versions (1.13.0. and 1.13.1): https://github.com/pnp/docker-spfx/blob/6a901466c7f82cb764db57bca65e012c2dd0386c/Dockerfile#L3

**Comment by waldekmastykarz** [comment]
Good catch! Let's remove it from the images where it's no longer necessary

**Comment by shurick81** [comment]
https://github.com/pnp/docker-spfx/pull/71
