### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by T0biii** [pnp/docker-spfx#74]
Hey, 
maybe you want to change the branch to main so its match the contributing guidelines or edit the contributing gudelines to match the commands under [Tips](https://github.com/pnp/docker-spfx/blob/master/CONTRIBUTING.md#tips)

- ensure that the **master** branch on your fork is in sync with the original **docker-spfx** repository
    ```sh
    # assuming you are in the folder of your locally cloned fork....
    git checkout master

    # assuming you have a remote named `upstream` pointing to the official **docker-spfx** repo
    git fetch upstream

    # update your local main to be a mirror of what's in the main repo
    git pull --rebase upstream master
    ```

**Comment by waldekmastykarz** [comment]
Good point! Thank you for bringing it up
