### ISSUE TITLE
No Template for an Improvement

### ISSUE THREAD

**Issue by shurick81** [pnp/docker-spfx#78]
**Describe the bug**
Impossible to register an improvement in this project

**To Reproduce**
1. Open https://github.com/pnp/docker-spfx/issues
2. Click `New issue`

**Expected behavior**
A choice of the issue type: a bug, or an improvement

**Screenshots**

**Desktop (please complete the following information):**
irrelevant

**Additional context**

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @shurick81. I wouldn't say it's impossible to suggest an improvement in this project, but perhaps it's not as convenient because we don't have a template for it. Do you have a suggestion what should it look like?

**Comment by shurick81** [comment]
I guess we could start with just empty template which would give the ipportunity to distinguish bugs from improvements. If we have a flood of improvements later, we could bring a better structure in place :)

**Comment by waldekmastykarz** [comment]
Empty template, isn't that the same as creating a blank issue using the existing option? After confirming that the issue is a bug indeed, and a question in disguise, we can tag it as such using labels. Would that work?

**Comment by shurick81** [comment]
Aha, my bad, I have not noticed the possibility to create a blank issue. So I guess we can just close this one :)
