### ISSUE TITLE
Improvement: Example of the devcontainer.json for Using the Image for Visual Studio Code Remote Containers Setup

### ISSUE THREAD

**Issue by shurick81** [pnp/docker-spfx#79]
It would be great to have an example of the devcontainer.json file that users can apply to their SPFx projects.

**Comment by waldekmastykarz** [comment]
Great idea! What would be the best place for it: code file in the repo + link from readme?

**Comment by waldekmastykarz** [comment]
If the contents wouldn't be too long, then we can absolutely add it to the existing readme and if need be, move to a separate file. Would you like to submit a PR?

**Comment by shurick81** [comment]
Yes, I will do soon

**Comment by shurick81** [comment]
PR: https://github.com/pnp/docker-spfx/pull/85
