### ISSUE TITLE
Gulp serve errored after

### ISSUE THREAD

**Issue by BrtSkr** [pnp/docker-spfx#87]
**Describe the bug**
After running gulp serve it stops right after starting tsc subtask

**To Reproduce**
1. Run 'gulp serve'
2. See error

**Screenshots**
1. https://prnt.sc/8Uqb95uS8GPv
2. https://prnt.sc/2e4qC7ZycTjy 

**Desktop:**
 - OS: Linux (Pop-OS)
 - Shell: Bash
 - Image version: latest 

**Additional context**
I already tried downgrading node, gulp to 3.9.1.

**Comment by shurick81** [comment]
what version of project are you trying to work with?
what image tag are you using?

**Comment by shurick81** [comment]
could you clone this project and follow the guidance and see how it works on your system?

https://github.com/shurick81/spfx-demo-01

**Comment by BrtSkr** [comment]
> @BrtSkr could you clone this project and follow the guidance and see how it works on your system?
> 
> https://github.com/shurick81/spfx-demo-01

Thanks for really quick reply, I cloned it and it works. I think I might have mistaken versions, if version inside readme is correct then I was on 1.13. Thanks for help!
