### ISSUE TITLE
Error running gulp serve in 1.15.2

### ISSUE THREAD

**Issue by Sartor87** [pnp/docker-spfx#98]
Describe the bug

Error occurs whenever I try to run gulp serve. This happens with a newly scaffolded project which is created from within the docker image.

` 'serve' errored after`

To Reproduce

1. Navigate to the project folder or an empty folder
2. Ensure that all changes to the node packages and config files are made per documentation
3. Run docker image with version 1.15.2

`docker run -it --rm --name spfx-helloworld -v %cd%:/usr/app/spfx -p 4321:4321 -p 35729:35729 m365pnp/spfx:1.15.2`

4. Run gulp trust-dev-cert
5. Run gulp serve

Error occurs
![image](https://github.com/pnp/docker-spfx/assets/11814675/7adc85ae-b326-4bb7-afba-788d68528367)

Expected behavior
The project should be run.

**Comment by shurick81** [comment]
Hi @Sartor87, where did you get the `node_modules` directory for this solution? I guess it should be generated by running `rpm install` and it is important that you run this command in the same image where you want to run `gulp serve`

**Comment by waldekmastykarz** [comment]
Closing due to lack of response
